# Generated by Django 6.0 on 2026-01-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField()),
                ('category', models.CharField(choices=[('inf', 'information'), ('wrn', 'warning'), ('crt', 'critical')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('category__in', ['inf', 'wrn', 'crt'])), name='category_validation')],
            },
        ),
    ]
