# Generated by Django 6.0 on 2026-01-01 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date')), ('start_date__gte', datetime.date(2026, 1, 1))), name='date_validation'),
        ),
    ]
