# Generated by Django 6.0 on 2026-01-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_date_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
