# Generated by Django 6.0 on 2026-01-01 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_alter_announcement_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='announcement',
            name='date_validation',
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date')), ('start_date__gte', datetime.datetime(2026, 1, 1, 3, 50, 26, 778018, tzinfo=datetime.timezone.utc))), name='date_validation'),
        ),
    ]
